### ISSUE TITLE
Upgrading from Orion

### ISSUE THREAD

**Issue by krishaamer** [scorpiusjs/scorpius#10]
I'm planning to upgrade my first app (https://www.artstories.gallery) from Orion to Scorpius next week. Is there a checklist of things to keep in mind beforehand when upgrading? I'll document if I'll encounter any errors.

Just looking at the repos the first thing that comes to mind is whether there's support for nicolaslopezj:orion-admin-only-bootstrap as I'm using Bootstrap for the admin and Semantic UI for the app itself.

Best,
Kris

**Comment by romans127** [comment]
Greetings,

Currently there is a package released that aims to add backwards compatibility essentially taking the Orion name space and passing it to the Scorpius namespace. I know this is not the most ideal solution but I wanted to ensure an easy transition for those who currently have projects on Orion and would like to start with Scorpius. I will also be writing an official migration guide shortly once I get a few major things worked out. 

I believe , still testing that if you are using modules, you might have to import the package at startup. I will be sure to test this before writing the guide.

https://atmospherejs.com/scorpiusjs/legacy-scope

**Comment by romans127** [comment]
On a side note. It will be as easy as replacing all variants of orion with scorpius. 
Package authors that originally created packages for orion will need to do the same and publish a variant of the package for scorpius.

**Comment by romans127** [comment]
If this answers your question i'm going to close this issue. New docs will be provided soon.
