### ISSUE TITLE
Using Scorpius with tap:i18n-db?

### ISSUE THREAD

**Issue by krishaamer** [scorpiusjs/scorpius#14]
Both want to initiate collections with their own prefix, for example TAPi18n.Collection and Scorpius.Collection. Is there a way around this in javascript or should one of the packages change for them to work together?

**Comment by romans127** [comment]
@krishaamer  I haven't looked this far into i18n-db , but there is already several language packages available, that use json to define the schema for the language. Maybe you could take a look at one of those packages and see if they are good starting points for what you are trying to accomplish. 

I'll take a closer look and see if Core can handle what you're trying to accomplish as well.

**Comment by krishaamer** [comment]
Hey @rwatts3 Do you mean to translate the UI? As far I've understood the TAP DB package is the only one dealing directly with content. So far I've rolled by own temporary solution by adding a language field to each piece of content and then filtering based on the user language on find(). It works however I think the TAP solution of storing translations within the same document could be cleaner in the long run if there's lots of content.

https://www.youtube.com/watch?v=cu_dsoIc_0E

**Comment by romans127** [comment]
Checking in on this issue. 
How did you get things working ?

**Comment by krishaamer** [comment]
For now using the "temporary" solution. I opened up the same issue at tap-i18n-db as well however it seems there's nobody really maintaining that package..

**Comment by romans127** [comment]
Ok very well. 

By the way nice work on the questions and answers site. 

As soon as the new project site is up, there will be a section for showcase projects, it'd be nice for you to submit to the showcase .
