### ISSUE TITLE
No admin links on sidebar

### ISSUE THREAD

**Issue by donmasakayan** [scorpiusjs/scorpius#16]
There are no admin links on the sidebar. No console errors. Also happens with latest version of Orion.

Meteor version: Meteor 1.4.1.1

Chrome:
<img width="300" alt="chrome" src="https://cloud.githubusercontent.com/assets/1178461/18406682/d8f2e3c4-76b4-11e6-8808-00dffb71397c.png">

Firefox:
<img width="300" alt="firefox" src="https://cloud.githubusercontent.com/assets/1178461/18406662/a3716ff4-76b4-11e6-87c0-a48d0a3ffe46.png">

**Comment by donmasakayan** [comment]
Unsure if related, but when I go to admin/accounts, there are no entries. Is this normal? I am currently logged in with an admin account that was created via `Accounts.createUser()`

<img width="300" alt="accounts" src="https://cloud.githubusercontent.com/assets/1178461/18406710/5565d1c8-76b5-11e6-9aea-8e2202df8dcf.png">

**Comment by romans127** [comment]
Can you run meteor reset ?

**Comment by ecuanaso** [comment]
Packages 
https://gist.github.com/ecuanaso/ef167ff80a8ee1566c6f1f1145ffda88

Versions 
https://gist.github.com/ecuanaso/ccba861ce44247b47d7007b7ccf9ba80

**Comment by romans127** [comment]
Ok , 

Most likely this problem is caused due to roles being assigned properly. Take a look at the original orion examples project for "blog" https://github.com/orionjs/examples . 

Once i've gotten things ironed out with Scorpius I will be writing documentation to help. With update examples and boilerplate projects. 

For now if you create a user without the proper role of admin, You will experience this issue.

**Comment by ecuanaso** [comment]
Ok the admin sidebar links show now. I had to do a meteor reset. navigate to localhost:3000/admin. 
And register a user with the proper admin role.

**Comment by romans127** [comment]
Yes, so signing up through the register form, ensures the proper role of `admin` is assigned to the first user. Also see the example project on how to define other role types. Again documentation will be coming soon for all of this. 

Closing this issue in lieu of @ecuanaso 's solution.

**Comment by JulianKingman** [comment]
If you're adding via robomongo or something, the proper role is: `"_id": "askfhgoahwrij", ..., "roles": ["admin"]`

**Comment by rwatts3** [comment]
are you trying to add a standalone link or trying to link to a collection item ?
