### ISSUE TITLE
Reference to the original project

### ISSUE THREAD

**Issue by nicolaslopezj** [scorpiusjs/scorpius#22]
Hi Ryan,

Could you please add a reference to the original project, I don't see the License and this is not a fork.

Because as it says in the license:

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

Thank you

**Comment by romans127** [comment]
He Lives !!

Done e49398f6e66821afc84a2d157500f1b5019bacc6

Would you be willing to add a message to the Orion readme stating its deprecation and encouragement to use the Scorpius Project for future development.  There are a lot of developers in the community that areleft with outlying issues in the Orion project .

Cheers
