### ISSUE TITLE
Error with SSL Meteor host on route /admin/my-account

### ISSUE THREAD

**Issue by mmazloum** [scorpiusjs/scorpius#31]
Hi,

This backend is hosted on galaxy, with SSL enabled, everything seems to work fine but I get this error in the console : 
![image](https://cloud.githubusercontent.com/assets/3626499/19084064/31e40daa-8a65-11e6-905f-60e1acd807f8.png)

just to let you know.

**Comment by romans127** [comment]
Interesting are you loading a script anywhere on your site. There shouldn't
be any third party scripts being called.  This is due to the fact that a
script is being loaded that is not secure. Can you see if you can hunt down
the script maybe parse the logs a little further.

**Comment by mmazloum** [comment]
I'll take a look and keep you posted

**Comment by mmazloum** [comment]
my mistake I had a remote connexion running on http.
