### ISSUE TITLE
Summernote doesn't work

### ISSUE THREAD

**Issue by mmazloum** [scorpiusjs/scorpius#32]
Hi,

This backend is hosted on galaxy, with SSL enabled, and summernote doesn't seem to work, texts are not recorded.

Here is the console trace : 
![image](https://cloud.githubusercontent.com/assets/3626499/19084207/daeb5bc4-8a65-11e6-980d-cae06261867a.png)

If I replace summernote attribute with a string in the scorpius schema, everything works fine.
I'll try froala and keep you posted.

All the best ;-)

**Comment by romans127** [comment]
Ok thank you. Let me know what you find

**Comment by mmazloum** [comment]
element.code(this.data.value); at line 31 in summernote.js seems to be responsible for that, maybe because they updated this package. Considering this i guess froala will work.

**Comment by romans127** [comment]
I will look into this further. Please monitor #20 , 
A major refactor is in place that will bring all core functionality under 1 package `scorpiusjs:scorpius` I will be upgrading all dependencies to the latest version, and fixing a great deal of these packages.

You will be able to settings and options via API classes. 

``` js
Meteor.startup(function () {
    new ScorpiusConfig({
        editors: {
            summernote: {
                ... summernote options using new summer 2.x api
            }
        }
    });
});
```

**Comment by mmazloum** [comment]
great, keep me posted if you need an early tester.

**Comment by romans127** [comment]
@mmazloum is this still an issue or were you able to find a solution ?

**Comment by mmazloum** [comment]
hi finally used Froala for other reasons, I may give it a try next week where I'll start a new project.

**Comment by romans127** [comment]
ok good deal i will close this issue for now, as I was not able to reproduce, and have not received other reports from the community. Feel free to open if the issue takes place in the future.

**Comment by mmazloum** [comment]
confirmed everything works fine !

**Comment by ahmadsholehin** [comment]
I unfortunately still couldn't get Summernote to work correctly without facing above error message. For those reading this issue, as a workaround, I used [mpowaga:autoform-summernote](https://atmospherejs.com/mpowaga/autoform-summernote) instead and configured the editor in such manner:

```
about: {
	type: String,
	label: "About",
	autoform: {
		afFieldInput: {
			type: "summernote",
			class: "editor",
			settings: {
				height: 300
			}
		}
	}
}
```
