### ISSUE TITLE
Migrate into  ostrio:files

### ISSUE THREAD

**Issue by chompomonim** [scorpiusjs/scorpius#37]
CollectionFS is deprecated, I think scorpius should consider migration into `ostrio:files` (https://github.com/vsivsi/meteor-file-collection/)

**Comment by loongmxbt** [comment]
Nice!

**Comment by romans127** [comment]
Hi @chompomonim 
Sorry it took so long for me to get back with you. 
This is an interesting topic. Have you attempted a PR yet ?

**Comment by romans127** [comment]
@chompomonim 
Feel free to submit a PR, for now i'll revisit this issue at a later date.
