### ISSUE TITLE
ReferenceError: i18n is not defined

### ISSUE THREAD

**Issue by krishaamer** [scorpiusjs/scorpius#39]
After updating to 0.3.1 I'm getting the following error:

```
W20161210-00:25:21.343(2)? (STDERR) ReferenceError: i18n is not defined
W20161210-00:25:21.343(2)? (STDERR)     at meteorInstall.node_modules.meteor.scorpiusjs:accounts.accounts.js (packages/scorpiusjs:accounts/accounts.js:69:23)
W20161210-00:25:21.344(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161210-00:25:21.344(2)? (STDERR)     at require (packages/modules-runtime.js:106:16)
```

**Comment by romans127** [comment]
Can you try to add the `lang-en` package directly. 
I removed the dependency in `core` this may be related to that.

**Comment by krishaamer** [comment]
Tried that but no difference unfortunately. Also tried adding anti:i18n, which is what I guess packages/scorpiusjs:accounts/accounts.js:69:23 is referring to but still getting the same reference error. Also tried creating a fresh meteor app to rule out any interference and getting the same error.

**Comment by romans127** [comment]
yeah i'm noticing this too with a fresh app, I updated the api version to 1.4.3.2 I wonder if it has something to do with that. anyhow i'm looking into the issue as we speak.

**Comment by krishaamer** [comment]
Thanks!

**Comment by romans127** [comment]
ok so far it definitely looks like the problem is with api version. i'll release a patch shortly once I finish testing

**Comment by romans127** [comment]
just pushed a release for `accounts`
give it a spin and let me know if everything checks out .

**Comment by krishaamer** [comment]
Yep, that solved it! Thanks!

**Comment by romans127** [comment]
Awesome.
